version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    environment:
      - DB_ADDR=db:6379
      - DB_PASS=
      - DOMAIN=localhost:3000
      - APP_PORT=:3000
      - API_QUOTA=10
    depends_on:
      - db
  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data